# Generated by Django 5.0.2 on 2024-12-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_list_name', models.CharField(max_length=255, unique=True)),
                ('field_list_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_list', models.CharField(max_length=30, unique=True)),
                ('source_list_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scheme_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_type', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=30, unique=True)),
                ('query_conditions', models.TextField(blank=True, null=True)),
                ('query_alias', models.CharField(blank=True, max_length=30, null=True)),
                ('query_description', models.TextField(blank=True, null=True)),
                ('field_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.fieldlist')),
                ('source_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=30)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_url', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=10, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('change_date', models.TextField(blank=True, null=True)),
                ('changed_by', models.TextField(blank=True, null=True)),
                ('report_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='storage.query')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(max_length=30)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule', models.ManyToManyField(blank=True, related_name='roles', to='storage.rule')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='default_rule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_metadata', to='storage.rule'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_alias', models.CharField(max_length=30)),
                ('source_type', models.CharField(choices=[('tbd', 'To be defined'), ('table', 'Table'), ('data_source', 'Data Source'), ('query', 'Query')], default='tbd', max_length=30)),
                ('table_name', models.CharField(blank=True, max_length=30, null=True)),
                ('union_condition', models.TextField(blank=True, max_length=255, null=True)),
                ('source_description', models.TextField(blank=True, null=True)),
                ('query_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.query')),
                ('source_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_names', to='storage.sourcelist')),
                ('source_union_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_list_names', to='storage.sourcelist')),
                ('source_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sourcescheme')),
                ('source_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sourcesystem')),
                ('union_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.uniontype')),
            ],
        ),
        migrations.AddField(
            model_name='fieldlist',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_alias', models.CharField(blank=True, max_length=30, null=True)),
                ('field_source_type', models.CharField(choices=[('tbd', 'To be defined'), ('data_source', 'Data Source'), ('function', 'Function'), ('value', 'Value')], default='tbd', max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=30, null=True)),
                ('field_value', models.CharField(blank=True, max_length=30, null=True)),
                ('field_function', models.TextField(blank=True, max_length=255, null=True)),
                ('function_field_list', models.CharField(blank=True, max_length=255, null=True)),
                ('field_description', models.TextField(blank=True, null=True)),
                ('field_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.fieldlist')),
                ('metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.metadata')),
                ('field_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.source')),
                ('source_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist')),
            ],
        ),
        migrations.AddField(
            model_name='sourcescheme',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sourcesystem'),
        ),
    ]
