# Generated by Django 5.0.1 on 2024-02-10 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_list_name", models.CharField(max_length=255)),
                (
                    "field_list_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_list_alias", models.CharField(max_length=30)),
                ("source_list_name", models.CharField(max_length=30)),
                ("source_list_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SourceScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_scheme_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="UnionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "union_type",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_alias", models.CharField(max_length=30)),
                (
                    "source_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("tbd", "To be defined"),
                                ("table", "Table"),
                                ("data_source", "Data Source"),
                                ("query", "Query"),
                            ],
                            default="tbd",
                            max_length=30,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("union_condition", models.CharField(max_length=255)),
                (
                    "source_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "source_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.sourcescheme",
                    ),
                ),
                (
                    "union_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.uniontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_alias", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "field_source_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("tbd", "To be defined"),
                                ("data_source_item", "Data Source"),
                                ("function", "Function"),
                                ("value", "Value"),
                            ],
                            default="tbd",
                            max_length=30,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "field_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "field_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.fieldlist",
                    ),
                ),
                (
                    "field_source_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storage.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_name", models.CharField(max_length=10)),
                (
                    "query_conditions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("query_alias", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "query_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "field_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.fieldlist",
                    ),
                ),
                (
                    "source_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.sourcelist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fieldlist",
            name="data_source_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.sourcelist",
            ),
        ),
        migrations.AddField(
            model_name="sourcescheme",
            name="source_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.sourcesystem",
            ),
        ),
    ]
