# Generated by Django 5.0.2 on 2025-01-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
