# Generated by Django 5.0.2 on 2025-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_query_query_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='query_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
