# Generated by Django 5.0.2 on 2025-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_source_query_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_query_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
