# Generated by Django 5.0.1 on 2024-02-10 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0003_alter_source_union_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_source_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("tbd", "To be defined"),
                        ("data_source_item", "Data Source"),
                        ("function", "Function"),
                        ("value", "Value"),
                    ],
                    max_length=30,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
