# Generated by Django 5.0.1 on 2024-02-10 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_alter_field_field_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("tbd", "To be defined"),
                        ("table", "Table"),
                        ("data_source", "Data Source"),
                        ("query", "Query"),
                    ],
                    max_length=30,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
