# Generated by Django 5.0.2 on 2025-01-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_field_field_query_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcescheme',
            name='source_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.sourcesystem'),
        ),
    ]
