# Generated by Django 5.0.2 on 2025-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_sourcescheme_source_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
