# Generated by Django 5.0.1 on 2024-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005_alter_source_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("tbd", "To be defined"),
                    ("table", "Table"),
                    ("data_source", "Data Source"),
                    ("query", "Query"),
                ],
                default="tbd",
                max_length=30,
            ),
        ),
    ]
