# Generated by Django 5.0.1 on 2024-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_alter_source_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_source_type",
            field=models.CharField(
                choices=[
                    ("tbd", "To be defined"),
                    ("data_source_item", "Data Source"),
                    ("function", "Function"),
                    ("value", "Value"),
                ],
                default="tbd",
                max_length=30,
            ),
        ),
    ]
