# Generated by Django 5.0.2 on 2025-01-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_query_query_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
