# Generated by Django 5.0.1 on 2024-02-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_alter_field_field_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.sourcesystem",
            ),
        ),
    ]
