# Generated by Django 5.0.2 on 2025-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcelist',
            name='source_list',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
