# Generated by Django 5.0.1 on 2024-02-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0008_source_source_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="source",
            name="object_id",
        ),
        migrations.AddField(
            model_name="source",
            name="query_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.query",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="source_list_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.sourcelist",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("tbd", "To be defined"),
                    ("table", "Table"),
                    ("source_list", "Source List"),
                    ("query", "Query"),
                ],
                default="tbd",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="table_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
