# Generated by Django 5.0.2 on 2025-02-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_query_query_name_alter_report_report_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('version_description', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.report')),
                ('report_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.query')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version'), name='field_constraint'),
        ),
    ]
