# Generated by Django 5.0.1 on 2024-02-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0009_remove_source_content_type_remove_source_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="field_list_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.fieldlist",
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="source_list_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.sourcelist",
            ),
        ),
    ]
