# Generated by Django 5.1.7 on 2025-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_report_report_script_reportversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='okta_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='source',
            field=models.CharField(choices=[('okta', 'Managed by Okta'), ('local', 'Managed by DGF')], default='local', max_length=30),
        ),
    ]
