# Generated by Django 5.1.7 on 2025-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_role_okta_id_role_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='OktaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
