# Generated by Django 5.1.7 on 2025-06-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_oktauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='source',
            field=models.CharField(choices=[('okta', 'Okta'), ('local', 'DGF')], default='local', max_length=30),
        ),
    ]
