# Generated by Django 5.1.7 on 2025-07-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_role_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.TextField(blank=True, unique=True)),
                ('dgf_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.report')),
            ],
        ),
    ]
