# Generated by Django 5.0.1 on 2024-02-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0012_alter_source_source_list_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_list_name",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.sourcelist",
            ),
            preserve_default=False,
        ),
    ]
