# Generated by Django 5.1.7 on 2025-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_proxyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
