# Generated by Django 5.1.7 on 2025-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_proxyreport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyreport',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
