# Generated by Django 5.1.7 on 2025-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_proxyreport_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyreport',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
