# Generated by Django 5.0.1 on 2024-02-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0015_source_source_list_name_source_source_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldlist",
            name="field_list_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="query",
            name="query_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sourcelist",
            name="source_list_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
