# Generated by Django 5.1.7 on 2025-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_proxyreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
