# Generated by Django 5.1.7 on 2025-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_source_type',
            field=models.CharField(choices=[('tbd', 'To be defined'), ('data_source', 'Data Source'), ('function', 'Function'), ('value', 'Value')], default='tbd', max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oktauser',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='okta_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='source',
            field=models.CharField(choices=[('okta', 'Okta'), ('local', 'DGF')], default='local', max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sourcescheme',
            name='source_scheme_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='source_system_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
