# Generated by Django 5.1.7 on 2025-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_alter_field_field_alias_alter_field_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
