# Generated by Django 5.1.7 on 2025-08-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_field_field_placeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_placeholder',
            new_name='placeholder',
        ),
    ]
