# Generated by Django 5.0.1 on 2024-02-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_rename_field_list_field_field_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_list_id',
        ),
        migrations.AddField(
            model_name='field',
            name='field_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.fieldlist'),
        ),
    ]
