# Generated by Django 5.0.1 on 2024-02-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_alter_field_field_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_source_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.source'),
        ),
    ]
