# Generated by Django 5.0.1 on 2024-02-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_alter_field_field_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldlist',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='fieldlist',
            name='field_list_name',
        ),
        migrations.AddField(
            model_name='fieldlist',
            name='data_source',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist'),
            preserve_default=False,
        ),
    ]
