# Generated by Django 5.0.1 on 2024-02-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_fieldlist_field_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='field_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.fieldlist'),
        ),
        migrations.AlterField(
            model_name='query',
            name='source_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist'),
        ),
        migrations.AlterField(
            model_name='source',
            name='union_source_list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_list_names', to='storage.sourcelist'),
        ),
        migrations.AlterField(
            model_name='sourcescheme',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sourcesystem'),
        ),
        migrations.AlterField(
            model_name='uniontype',
            name='union_type',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
