# Generated by Django 5.0.1 on 2024-02-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0026_alter_query_field_list_id_alter_query_source_list_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='field_list_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='source_list_id',
        ),
        migrations.AddField(
            model_name='query',
            name='field_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.fieldlist'),
        ),
        migrations.AddField(
            model_name='query',
            name='source_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist'),
        ),
        migrations.AlterField(
            model_name='fieldlist',
            name='field_list_name',
            field=models.CharField(max_length=255),
        ),
    ]
