# Generated by Django 5.0.1 on 2024-02-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0027_remove_query_field_list_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='union_source_list_name',
            new_name='source_union_list_name',
        ),
    ]
