# Generated by Django 5.0.2 on 2024-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_rename_union_source_list_name_source_source_union_list_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('source_union_list_name', 'source_alias')},
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('source_union_list_name', 'source_alias'), name='unique_source'),
        ),
    ]
