# Generated by Django 5.0.2 on 2024-02-18 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_alter_source_unique_together_source_unique_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_source_name',
            new_name='field_data_source',
        ),
        migrations.AddField(
            model_name='field',
            name='field_function',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='field',
            name='field_function_fields',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='field',
            name='field_value',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='field',
            name='source_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sourcelist'),
            preserve_default=False,
        ),
    ]
