# Generated by Django 5.0.2 on 2024-02-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0030_rename_field_source_name_field_field_data_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='source',
            name='unique_source',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='field_function_fields',
            new_name='function_field_list',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
    ]
