# Generated by Django 5.0.2 on 2024-02-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_remove_source_unique_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_data_source',
            new_name='field_source',
        ),
    ]
