# Generated by Django 5.0.2 on 2024-02-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_remove_field_field_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_function',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_conditions',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='union_condition',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
