# Generated by Django 5.0.2 on 2024-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_alter_field_field_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(default='tbd', max_length=30),
        ),
    ]
