# Generated by Django 5.0.2 on 2024-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('tbd', 'To be defined'), ('table', 'Table'), ('data_source', 'Data Source'), ('query', 'Query')], default='tbd', max_length=30),
        ),
    ]
