# Generated by Django 5.0.2 on 2024-03-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_alter_field_field_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
