# Generated by Django 5.0.2 on 2024-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0040_alter_field_field_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_function',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
