# Generated by Django 5.0.2 on 2024-05-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0045_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
