# Generated by Django 5.0.2 on 2024-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0050_alter_report_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
