# Generated by Django 5.0.2 on 2024-05-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0052_rename_source_list_name_source_source_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcelist',
            old_name='source_list_name',
            new_name='source_list',
        ),
    ]
