"""
Django settings for dgFramework project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os
import platform

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development. Variables already present in the real
# environment (Vault-injected in Kubernetes) always take precedence.
load_dotenv(BASE_DIR / ".env")


def _require_env(name):
    """Return a mandatory setting, failing loudly instead of falling back."""
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(
            f"{name} is not set. Copy .env.example to .env and fill it in, or "
            f"provide the variable through the deployment environment."
        )
    return value


def _env_flag(name, default=False):
    """Read a boolean setting from the environment."""
    return os.environ.get(name, str(default)).strip().lower() in ("1", "true", "yes", "on")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No fallback on purpose: a default here would let the app boot in production
# with a publicly known key instead of failing.
SECRET_KEY = _require_env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag("DEBUG", default=False)

# Public base URL of this deployment, also used for CORS and CSRF below.
HOST = os.environ.get("HOST", "http://localhost:8000").rstrip("/")

# An explicit ALLOWED_HOSTS wins; otherwise derive the hostname from HOST.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    _host_name = urlparse(HOST).hostname
    if _host_name and _host_name not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host_name)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storage",
    "dm",
    'corsheaders',
    # 'mozilla_django_oidc',
    # "import",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'mozilla_django_oidc.middleware.SessionRefresh',
]

_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://0.0.0.0:8000",
]
if HOST not in _TRUSTED_ORIGINS:
    _TRUSTED_ORIGINS.append(HOST)

CORS_ALLOWED_ORIGINS = list(_TRUSTED_ORIGINS)

CSRF_TRUSTED_ORIGINS = list(_TRUSTED_ORIGINS)

ROOT_URLCONF = "dgFramework.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dgFramework.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("DB_NAME", "dg_bae"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": _require_env("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
#     # 'storage.backends.MyOIDCAuthenticationBackend',
# ]

# OIDC Configuration (mozilla-django-oidc), currently disabled.
# Credentials must be read from the environment — never inlined here.
# OIDC_RP_CLIENT_ID = os.environ['OIDC_RP_CLIENT_ID']
# OIDC_RP_CLIENT_SECRET = os.environ['OIDC_RP_CLIENT_SECRET']
# OIDC_OP_AUTHORIZATION_ENDPOINT = f'{OKTA_DOMAIN}/oauth2/default/v1/authorize'
# OIDC_OP_TOKEN_ENDPOINT = f'{OKTA_DOMAIN}/oauth2/default/v1/token'
# OIDC_OP_USER_ENDPOINT = f'{OKTA_DOMAIN}/oauth2/default/v1/userinfo'
# OIDC_OP_JWKS_ENDPOINT = f'{OKTA_DOMAIN}/oauth2/default/v1/keys'
# OIDC_RP_SIGN_ALGO = 'RS256'
# LOGIN_URL = '/oidc/authenticate/'

if platform.system() == "Windows":
    OKTA_DOMAIN = "https://dev-04812975.okta.com"
    CLIENT_ID = "0oalk1pa5nk7rvIGq5d7"
    PROXY_HOST = "https://bae-be.webarkit.com"

else:
    OKTA_DOMAIN = "https://eu-bankaletihad.okta.com"
    CLIENT_ID = "0oanqdcd6k9nLoAp9417"
    PROXY_HOST = "https://reports-govern.baelab.net/"
    # PROXY_HOST = "https://reports-govern.bankaletihad.com"

JWKS_URL = f"{OKTA_DOMAIN}/oauth2/v1/keys"

LOGIN_URL = '/storage/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Ensure UTF-8 encoding is used
# os.environ['PYTHONIOENCODING'] = 'utf-8'
