[uwsgi]
# Set the Python module to be loaded
module = dgFramework.wsgi:application

# Enable master process for managing workers
master = true

# Set the number of worker processes (adjust based on available resources)
processes = 1
threads = 2

# Bind to a socket (uWSGI will communicate over this socket with the web server)
socket = 0.0.0.0:8000

# Ensure that the uWSGI process terminates when it receives a signal
die-on-term = true

# Enable automatic cleanup
vacuum = true

# Enable logging
logto = /var/log/uwsgi/uwsgi.log

# Set the environment variable for Django settings module
env = DJANGO_SETTINGS_MODULE=dgFramework.settings

# Static file handling (adjust paths accordingly)
static-map = /static=/app/static
