image: 
  repository: data-governance
  registry: 310899098394.dkr.ecr.eu-west-2.amazonaws.com
  tag: "36e8ca2"
  pullPolicy: Always


service:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    protocol: TCP

initContainers:
- name: db-migration
  image: 310899098394.dkr.ecr.eu-west-2.amazonaws.com/data-governance
  tag: "36e8ca2"
  command: ["/bin/sh", "-c", "/app/scripts/init.sh"]

deployment:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "http://vault.vault.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-skip-verify: "true"

  env:
  - name: DB_NAME
    value: "vault:secret/data/data-governance#DB_NAME"
  - name: DB_USER
    value: "vault:secret/data/data-governance#DB_USER"
  - name: DB_PASSWORD
    value: "vault:secret/data/data-governance#DB_PASSWORD"
  - name: DB_HOST
    value: "vault:secret/data/data-governance#DB_HOST"
  - name: DB_PORT
    value: "vault:secret/data/data-governance#DB_PORT"
  - name: DJANGO_SECRET_KEY
    value: "vault:secret/data/data-governance#DJANGO_SECRET_KEY"
  - name: DJANGO_SUPERUSER_USERNAME
    value: "vault:secret/data/data-governance#DJANGO_SUPERUSER_USERNAME"
  - name: DJANGO_SUPERUSER_EMAIL
    value: "vault:secret/data/data-governance#DJANGO_SUPERUSER_EMAIL"
  - name: DJANGO_SUPERUSER_PASSWORD
    value: "vault:secret/data/data-governance#DJANGO_SUPERUSER_PASSWORD"
  - name: HOST
    value: "vault:secret/data/data-governance#HOST"



  resources:
    limits:
      cpu: "1"
    requests:
      cpu: "0.5"

  tolerations:
  - key: dedicated
    value: apps
    operator: Equal
    effect: NoSchedule

hpa:
  enabled: true
  min: 1
  max: 10
  cpu: 60
  # mem: 60
  # pods: 1k # Packets per second
  # ingress: 10K # Requests per second

ingress:
  enabled: true
  annotations:
    # nginx.ingress.kubernetes.io/proxy-body-size: 100m
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "Cache-Control: max-age=86400";
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  ingressClassName: nginx-internal
  hosts:
    - host: datagov.baelab.net
      paths:
      - path: /
        backend:
          serviceName: data-governance
          servicePort: 8000

          
livenessProbe:
  httpGet:
    path: /api/wp-json/v1/health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 1
readinessProbe:
  httpGet:
    path: /api/wp-json/v1/health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 1
  failureThreshold: 3
  timeoutSeconds: 1